### ISSUE TITLE
Link to documentation is broken.

### ISSUE THREAD

**Issue by matedealer** [Ext-Creators/discord-ext-ipc#36]
### Description

The link to the documentation in the README.rst only leads to a page saying that the page doesn't exist.

### Expected Behavior
I would like to see documentation of the project there.

### Checklist

- [x] I have searched open issues for duplicates.
- [x] I have shown the entire traceback, if applicable.
- [x] I have removed any access tokens from display, if applicable.

**Comment by ShineyDev** [comment]
There's a new link there now. Thanks for the reminder.
