### ISSUE TITLE
IPC Route reloading maintains old routes (can maintain)

### ISSUE THREAD

**Issue by Skelmis** [Ext-Creators/discord-ext-ipc#45]
### Description
When reloading a cog with IPC routes, they will reload as expected. However if you change the name of the function (Or `name=` in decor), then this new route will be added to IPC as expected. However, the old route will also still exist.

### Actual Behavior
The old route isn't removed as the underlying key changed for said func

### Expected Behavior
The old route is removed

### Reproduction Steps
1. Run your bot, using the below cog example

```python
@ipc.server.route()
    async def get_member_count(self, data):
        guild = self.bot.get_guild(data.guild_id)  # get the guild object using parsed guild_id

        return guild.member_count  # return the member count to the client
```
2. Change the code to below once ipc loads
```python
@ipc.server.route(name="test")
    async def get_member_count(self, data):
        guild = self.bot.get_guild(data.guild_id)  # get the guild object using parsed guild_id

        return guild.member_count  # return the member count to the client
```

3. IPC *should* have `1` route (test), expect it has `2` (test, get_member_count)

### Additional Context
I'm not sure how to fix this, hence why I am opening an issue and not a pull request.

### Checklist
- [x] I have searched open issues for duplicates.
- [x] I have shown the entire traceback, if applicable.
- [x] I have removed any access tokens from display, if applicable.

### System Information
IPC: Latest on main
System independant

**Comment by lgaan** [comment]
Closing in favour of #44
