### ISSUE TITLE
_MissingSentinel has no attribute 'request'

### ISSUE THREAD

**Issue by St0rmdev** [Ext-Creators/discord-ext-ipc#51]
### Description
Hello. When I try to get bot servers (bot.guilds) I get an empty list. When I want to fetch the servers using ` bot.fetch_guilds().flatten()`, I get the error given in the issue title.

### Actual Behavior
AttributeError: '_MissingSentinel' object has no attribute 'request'
File C:\Users\main\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\http.py, line 354

### Expected Behavior
Guild list

### Reproduction Steps
I described it in the description

### Additional Context
I'm using discord.py 2.0 beta.

### Function code
![image](https://user-images.githubusercontent.com/81083382/127642525-cb01177a-1d47-4915-a51b-9fef4136bc10.png)

### Checklist
- [x] I have searched open issues for duplicates.
- [x] I have shown the entire traceback, if applicable.
- [x] I have removed any access tokens from display, if applicable.

### System Information
Windows 11 BETA, latest version
Python 3.9

**Comment by iamsador** [comment]
*i have all intents enabled

**Comment by iamsador** [comment]
i fixed my problem, but bot.guilds is still empty list

**Comment by jgayfer** [comment]
This is not an issue with discord-ext-ipc
